import '@/app/globals.css';
import '@/styles/style.scss';
import type { Metadata } from 'next';
import SNSettingsNav from '@/components/ui/SNSettingsNav';

export const metadata: Metadata = {
  title: 'SendNest',
  // description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className="px-3">
        <h3 className="pb-6 pt-11 text-2xl font-medium lg:pt-0">Settings</h3>

        <div className="flex flex-col gap-10 lg:w-full lg:flex-row xl:gap-20">
          <SNSettingsNav />

          <div className="w-full lg:w-[65%] xl:w-[75%] 2xl:w-4/5">{children}</div>
        </div>
      </div>
    </>
  );
}
