import './globals.css'
import '../styles/style.scss'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Providers} from "@/app/providers";
import Head from 'next/head'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <Head>
            <title></title>
            {/* eslint-disable-next-line @next/next/no-page-custom-font */}
            <link rel="stylesheet"
                  href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Radio+Canada:wght@300;400;500;600;700&display=swap"/>
        </Head>
        <body>
        <Providers>
            {children}
        </Providers>
        </body>
        </html>
    )
}
